### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by nshoa99** [GlenGGG/FTP#1]
Hi, can I run this project on Window. 
Many thanks

**Comment by GlenGGG** [comment]
Sorry, you can't. I use Linux system calls like "chdir", also the socket mechanism is different from Windows, so you can't directly use it on Windows. I'll make it clear in the readme. Thanks for opening this issue.

**Comment by nshoa99** [comment]
Could you please show me the references or the source code that you follow?

**Comment by GlenGGG** [comment]
I think you can find docs for all the system calls plus socket programming for Linux in [Linus man page](https://man7.org/linux/man-pages/index.html), or just Google it. Most FTP functionalities (like list, stor, cdup) in this project are implemented in [here](https://github.com/GlenGGG/FTP/blob/master/ftp-server/src/server_command.c).

**Comment by nshoa99** [comment]
Thank you so much.
